### ISSUE TITLE
Alphabetical media query ordering

### ISSUE THREAD

**Issue by kpatient** [blakeembrey/free-style#19]
I'm surprised I've not been able to find this issue anywhere, so maybe I've missed something.

So css declarations are sorted alphabetically when output. This also applies to `@media` queries which can cause them to override each other.

Example: 
```javascript
	item: {
		width: "20rem",
		'@media screen and (min-width: 500px)' : {
			width: '500px'
		},
		'@media screen and (min-width: 1000px)' : {
			width: '1000px'
		},
	},
```

This is outputting in this order for me, which I think is because it is reading the 1000 before the 500:
```css
@media only all and (min-width: 500px) .f1hawebh {
    max-width: 500px;
}

@media only all and (min-width: 1000px) .f1hawebh {
    max-width: 1000px;
}
```
