### ISSUE TITLE
Vendor-Prefixed unitless values get 'px' appended

### ISSUE THREAD

**Issue by namuol** [blakeembrey/free-style#2]
Example style:

```js
{
  flexGrow: 2,
  WebkitFlexGrow: 2,
}
```

Produces this style:

```css
.foo {
  flex-grow: 2;
  -webkit-flex-grow: 2px;
}
```

There's no real workaround, either. I've tried changing my code to this:

```js
{
  flexGrow: '2',
  WebkitFlexGrow: '2',
}
```

...but it still treats the `'2'` as a number and appends the `'px'` unit.

Am I missing something?
