### ISSUE TITLE
How to enforce "uniqueness" / separate outputs?

### ISSUE THREAD

**Issue by Frikki** [blakeembrey/free-style#39]
I’ve encountered an issue that I don’t know how to solve. Actually, I use TypeStyle, but I believe it may have free-style answer. If it’s too foreign, just close the issue. I have already opened an [issue in TypeStyle](https://github.com/typestyle/typestyle/issues/26), but it has not yet been addressed, so I am trying here.

Note: `style(object)`  is similar to `registerStyle`.

```javascript
const MyStyle = style({
  color: 'blue',
  '&::-webkit-input-placeholder': {
    color: `rgba(0, 0, 0, 0)`
  },
  '&::-moz-placeholder': {
    color: `rgba(0, 0, 0, 0)`
  },
  '&::-ms-input-placeholder': {
    color: `rgba(0, 0, 0, 0)`
  }
}); // => f13byakl
```

This outputs the following styles:

```css
.f13byakl{color:blue}
.f13byakl::-webkit-input-placeholder,
.f13byakl::-moz-placeholder,
.f13byakl::-ms-input-placeholder{color:rgba(0, 0, 0, 0)}
```

The problem is, however, that browsers do not understand:

```css
.f13byak::-webkit-input-placeholder, /* WebKit fails here */
.f13byak::-moz-placeholder,          /* Firefox fails here */
.f13byak::-ms-input-placeholder {    /* IE fails here */
    color: rgba(0, 0, 0, 0);
}
```

To make this work,  the final CSS must look like this:

```css
.f13byak::-webkit-input-placeholder {
    color: rgba(0, 0, 0, 0);
}
.f13byak::-moz-placeholder {
    color: rgba(0, 0, 0, 0);
}
.f13byak::-ms-input-placeholder {
    color: rgba(0, 0, 0, 0);
}
```

How is it possible to enforce this output?
