### ISSUE TITLE
Support commas in nested rules

### ISSUE THREAD

**Issue by pedro-pedrosa** [blakeembrey/free-style#69]
When trying to extend third-party CSS rules using free-style you may run into a scenario like this:

```js
const style = FreeStyle.create();
const className = style.registerStyle({
    '& .third-party-input, & .third-party-button': {
        '&:hover': {
            backgroundColor: 'transparent'
        },
        marginLeft: 10
    }
});
```
This, however, does not work as expected for the :hover rule. The emitted CSS looks something like this:
```css
.f1si452i .third-party-input, .f1si452i .third-party-button {
    margin-left:10px
}
.f1si452i .third-party-input, .f1si452i .third-party-button:hover {
    background-color:transparent
}
```
Note the missing :hover after .third-party-input in the second rule. This works fine in other CSS preprocessors though (less, sass) so I believe it would be a nice addition to this library replacing the current string replacement logic. Probably just splitting the parent selector and mapping the string replacement function to each element of the splitted selector would suffice here?
