### ISSUE TITLE
Interpolation question with deep nest

### ISSUE THREAD

**Issue by whitecolor** [blakeembrey/free-style#72]
Was asked originally at https://github.com/typestyle/typestyle/issues/292

For such style definition:
```ts
Style.registerStyle({
    '& .c1, & .c2': {      
        '&:hover,&:active': {
            '& .nested': {
              opacity: '0.15'
            }
        },
    },
})
```
The generated CSS:

```css
.generated .c1, 
.generated .c2:hover,
.generated .c1, 
.generated .c2:active .nested {
    opacity:0.15
}
```
I wonder in't it more reasonable to get:

```css
.generated .c1:hover .nested, 
.generated .c1:active .nested, 
.generated .c2:hover .nested, 
.generated .c2:active .nested {
    opacity:0.15
}
```

Currently `& .c1, & .c2` is applied to `generated`, then `&:hover,&:active` applied to the last of interpolated parts, and so on? Is it how it should be in your view? What would be unlogical if it would apply interpolation to all previous interpolated parts (like most of the things like LESS/SASS do)?
